check_rules <<'---';
PROJECTION_SEQUENCES, LOWEST_PROJECTION_DIMENSION : VERTICES, FACETS, VERTICES_IN_FACETS, DUAL_GRAPH.ADJACENCY, CONE_AMBIENT_DIM, CONE_DIM
1

LOWEST_PROJECTION_DIMENSION, LOWEST_PROJECTION_SEQUENCE : VERTICES, FACETS, VERTICES_IN_FACETS, DUAL_GRAPH.ADJACENCY, CONE_AMBIENT_DIM, CONE_DIM
1

LOWEST_PROJECTION_DIMENSION : PROJECTION_SEQUENCES, CONE_DIM
1

SUBDIVISION.LATTICE_SUBDIVISION : VERTICES, FACETS, SUBDIVISION.SUBDIVISION_HYPERPLANES
2

SUBDIVISION.VALID_PROJECTION_COORDINATES : FACETS
1 2

SUBDIVISION.CELLS : SUBDIVISION.SUBDIVISION_HYPERPLANES, SUBDIVISION.LATTICE_SUBDIVISION, LATTICE_POINTS, FACETS, VERTICES
2

---
